repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.10
    hooks:
      - id: uv-lock

  - repo: https://github.com/ikamensh/flynt/
    rev: 1.0.6
    hooks:
      - id: flynt

  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: "7.0.0"
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/pylint
    rev: v4.0.3
    hooks:
      - id: pylint
        alias: pylint-with-spelling
        stages: [manual]
        language: system
        types: [python]
        require_serial: true
        exclude: (?x)^(
          doc/.*|
          tests/.*
          )$

  - repo: https://github.com/zmoon/findent-pre-commit
    rev: 527f61f770f504abd87f97932b510b8dce07ab3a
    hooks:
      - id: wfindent-system
        args:
          [
            -ofree,
            -i3,
            --indent_contains=restart,
            --indent_continuation=default,
            --indent_ampersand,
            --align_paren,
            --refactor_end,
          ]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.10.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
