[check]
# E - Error
# C - correctness
# S - Style
select = ["E", "C", "S"]
ignore = [
    "C003", # missing-external
    "C061", # missing-intent
    "C092", # procedure-not-in-module
]
line-length = 120
